version: "3.7"
services:
  grafana-metal-postgres:
    container_name: grafana-metal-postgres
    image: postgres:12
    ports:
     - 5431:5432
    volumes:
      - /var/postgres_container_data/metal_grafana_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: metal_user
      POSTGRES_PASSWORD: test
      POSTGRES_DB: metal
    network_mode: default
  
  metal-data:
    container_name: metal-postgres
    image: postgres:12
    ports:
     - 5430:5432
    volumes:
      - /var/postgres_container_data/metal_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: metal
      POSTGRES_PASSWORD: test
      POSTGRES_DB: metal_db
    network_mode: default

  grafana:
    container_name: grafana-compose
    image: grafana/grafana:latest
    ports:
      - 3001:3000
      - 10000:10000
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
    volumes:
      - /var/grafana/data:/var/lib/grafana 
      - /var/grafana/grafana.ini:/etc/grafana/grafana.ini
    links:
      - metal-data
      - grafana-metal-postgres
    network_mode: default
